"""empty message

Revision ID: 592cf2fc215d
Revises: b9a833c06e1e
Create Date: 2023-06-02 12:37:36.897976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592cf2fc215d'
down_revision = 'b9a833c06e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
